openapi: 3.0.2
info:
  version: '0.1'
  title: 'magicapp3'
  description: magicapp3
servers:
  - url: /99999/magicapp3
    description: magicapp3
paths:
  /magicapp:
    post:
      description: magicapp3
      operationId: magicapp3
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/basicerror.yaml'
components:
  schemas:
    input:
      required:
        - reperfusion_eligible
      properties:
        reperfusion_eligible:
          type: boolean
          example: false
        # patient.features:
        #   type: array
          # items:
            # $ref: 'https://demo.kgrid.org/schemas/patientFeature.yaml'
    output:
      required:
        - op
      properties:
        result:
          type: object
